apiVersion: v1
kind: Service
metadata:
  name: boxing-service
#  annotations:
 #     service.beta.kubernetes.io/aws-load-balancer-type: external
  #    ervice.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
   #   service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: boxing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer